"""CoreGateway contracts and the Rust process backend."""

from .base import CoreGateway
from .contracts import (
    AcceptHypothesisCommand,
    AcceptHypothesisResult,
    ContextViewItem,
    ContextViewResult,
    CoreCapabilityError,
    CoreGatewayError,
    CoreHealth,
    DomainRejectedError,
    HypothesisEvidence,
    HypothesisExtraction,
    HypothesisPayload,
    RecordContextUsageCommand,
    RetrieveContextCommand,
    TransientCoreError,
)
from .maintenance import (
    BackupManifest,
    CoreMaintenanceRunner,
    CoreRestoreError,
    CreateBackupCommand,
    PrepareRestoreCommand,
    PrepareRestoreResult,
    ValidateBackupCommand,
)
from .model_task_contracts import (
    CoreModelTask,
    FailModelTaskCommand,
    FailModelTaskResult,
    PollModelTasksCommand,
    PollModelTasksResult,
    SubmitModelResult,
    SubmitModelResultCommand,
)
from .process import ProcessCoreGateway
from .projection_contracts import (
    AckProjectionEventsCommand,
    AckProjectionEventsResult,
    CoreProjectionEvent,
    PollProjectionEventsCommand,
    PollProjectionEventsResult,
)

__all__ = [
    "AcceptHypothesisCommand",
    "AcceptHypothesisResult",
    "AckProjectionEventsCommand",
    "AckProjectionEventsResult",
    "BackupManifest",
    "ContextViewItem",
    "ContextViewResult",
    "CoreCapabilityError",
    "CoreGateway",
    "CoreGatewayError",
    "CoreHealth",
    "CoreMaintenanceRunner",
    "CoreModelTask",
    "CoreProjectionEvent",
    "CoreRestoreError",
    "CreateBackupCommand",
    "DomainRejectedError",
    "FailModelTaskCommand",
    "FailModelTaskResult",
    "HypothesisEvidence",
    "HypothesisExtraction",
    "HypothesisPayload",
    "PollModelTasksCommand",
    "PollModelTasksResult",
    "PollProjectionEventsCommand",
    "PollProjectionEventsResult",
    "PrepareRestoreCommand",
    "PrepareRestoreResult",
    "ProcessCoreGateway",
    "RecordContextUsageCommand",
    "RetrieveContextCommand",
    "SubmitModelResult",
    "SubmitModelResultCommand",
    "TransientCoreError",
    "ValidateBackupCommand",
]
